FROM apache/airflow:2.7.1

# Switch to airflow user to install packages
USER airflow

# Install Python packages
RUN pip install --no-cache-dir hdfs pandas

# Switch back to airflow user (optional, already set)
USER airflow
